# Generated by Django 3.2.13 on 2022-08-04 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(verbose_name='Время начала')),
                ('title', models.CharField(max_length=200, verbose_name='название мероприятия')),
                ('event_type', models.CharField(choices=[('SP', 'Speech'), ('OT', 'Other')], default='OT', max_length=2, verbose_name='Тип')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Группа')),
            ],
        ),
        migrations.CreateModel(
            name='Guesttik',
            fields=[
                ('telegram_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Speech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='выступление')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='speeches', to='meetup_db.event', verbose_name='мероприятие_блок')),
            ],
        ),
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('telegram_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50, verbose_name='Имя спикера')),
                ('position', models.CharField(max_length=50, verbose_name='Должность')),
                ('organization', models.CharField(max_length=50, verbose_name='Название организации')),
                ('speeches_at_event', models.ManyToManyField(related_name='speakers_at_speech', to='meetup_db.Speech', verbose_name='Выступления')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='meetup_db.group', verbose_name='группа'),
        ),
    ]
