# Generated by Django 3.2.13 on 2022-08-04 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetup_db', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Guesttik',
            new_name='Guest',
        ),
    ]
